### ISSUE TITLE
KeyError with `InferenceData.to_netcdf`

### ISSUE THREAD

**Issue by michaelosthege** [arviz-devs/arviz#1830] opened 2021-10-01 15:08 UTC
**Describe the bug**
My collaboration partners ran into this when trying to do `idata.to_netcdf`.

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~\anaconda3\envs\CARenv\lib\site-packages\xarray\backends\file_manager.py in _acquire_with_cache_info(self, needs_lock)
    198             try:
--> 199                 file = self._cache[self._key]
    200             except KeyError:

~\anaconda3\envs\CARenv\lib\site-packages\xarray\backends\lru_cache.py in __getitem__(self, key)
     52         with self._lock:
---> 53             value = self._cache[key]
     54             self._cache.move_to_end(key)

KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('C:\\Git Repos\\CarbtModel\\notebooks\\NikolasNC.nc',), 'a', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False))]

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_1096/4099136273.py in <module>
----> 1
```

The file was created and contains a `posterior` group, but other groups like sampler stats are missing.

Any ideas?

ArviZ version: 0.11.2

**Comment by ahartikainen** [comment] 2021-10-19 06:19
What kind of data the object contains? Maybe there is some reference to an object that fails? Or maybe the number format is not the basic python/numpy but something more exotic like tensorflow etc?

**Comment by lhelleckes** [comment] 2021-10-19 09:26
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~\AppData\Local\Continuum\miniconda3\envs\dibecs_6.0.1\lib\site-packages\xarray\backends\file_manager.py in _acquire_with_cache_info(self, needs_lock)
    198             try:
--> 199                 file = self._cache[self._key]
    200             except KeyError:

~\AppData\Local\Continuum\miniconda3\envs\dibecs_6.0.1\lib\site-packages\xarray\backends\lru_cache.py in __getitem__(self, key)
     52         with self._lock:
---> 53             value = self._cache[key]
     54             self._cache.move_to_end(key)

KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('C:\\Users\\helleckes\\Repos\\cutisplit\\notebooks\\C4PZHQ_Results\\C4PZHQ_result_test.nc',), 'a', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False))]

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
C:\Users\HELLEC~1\AppData\Local\Temp/ipykernel_15308/4039754669.py in <module>
----> 1 idata.to_netcdf(fr"{resultpath}\{RUN_ID}_result_test.nc")

~\AppData\Local\Continuum\miniconda3\envs\dibecs_6.0.1\lib\site-packages\arviz\data\inference_data.py in to_netcdf(self, filename, compress, groups)
    390                 if compress:
    391                     kwargs["encoding"] = {var_name: {"zlib": True} for var_name in data.variables}
--> 392                 data.to_netcdf(filename, mode=mode, group=group, **kwargs)
    393                 data.close()
    394                 mode = "a"

~\AppData\Local\Continuum\miniconda3\envs\dibecs_6.0.1\lib\site-packages\xarray\core\dataset.py in to_netcdf(self, path, mode, format, group, engine, encoding, unlimited_dims, compute, invalid_netcdf)
   1898         from ..backends.api import to_netcdf
   1899 
-> 1900         return to_netcdf(
   1901             self,
   1902             path,

~\AppData\Local\Continuum\miniconda3\envs\dibecs_6.0.1\lib\site-packages\xarray\backends\api.py in to_netcdf(dataset, path_or_file, mode, format, group, engine, encoding, unlimited_dims, compute, multifile, invalid_netcdf)
   1058                 f"unrecognized option 'invalid_netcdf' for engine {engine}"
   1059             )
-> 1060     store = store_open(target, mode, format, group, **kwargs)
   1061 
   1062     if unlimited_dims is None:

~\AppData\Local\Continuum\miniconda3\envs\dibecs_6.0.1\lib\site-packages\xarray\backends\netCDF4_.py in open(cls, filename, mode, format, group, clobber, diskless, persist, lock, lock_maker, autoclose)
    378             netCDF4.Dataset, filename, mode=mode, kwargs=kwargs
    379         )
--> 380         return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
    381 
    382     def _acquire(self, needs_lock=True):

~\AppData\Local\Continuum\miniconda3\envs\dibecs_6.0.1\lib\site-packages\xarray\backends\netCDF4_.py in __init__(self, manager, group, mode, lock, autoclose)
    326         self._group = group
    327         self._mode = mode
--> 328         self.format = self.ds.data_model
    329         self._filename = self.ds.filepath()
    330         self.is_remote = is_remote_uri(self._filename)

~\AppData\Local\Continuum\miniconda3\envs\dibecs_6.0.1\lib\site-packages\xarray\backends\netCDF4_.py in ds(self)
    387     @property
    388     def ds(self):
--> 389         return self._acquire()
    390 
    391     def open_store_variable(self, name, var):

~\AppData\Local\Continuum\miniconda3\envs\dibecs_6.0.1\lib\site-packages\xarray\backends\netCDF4_.py in _acquire(self, needs_lock)
    381 
    382     def _acquire(self, needs_lock=True):
--> 383         with self._manager.acquire_context(needs_lock) as root:
    384             ds = _nc4_require_group(root, self._group, self._mode)
    385         return ds

~\AppData\Local\Continuum\miniconda3\envs\dibecs_6.0.1\lib\contextlib.py in __enter__(self)
    111         del self.args, self.kwds, self.func
    112         try:
--> 113             return next(self.gen)
    114         except StopIteration:
    115             raise RuntimeError("generator didn't yield") from None

~\AppData\Local\Continuum\miniconda3\envs\dibecs_6.0.1\lib\site-packages\xarray\backends\file_manager.py in acquire_context(self, needs_lock)
    185     def acquire_context(self, needs_lock=True):
    186         """Context manager for acquiring a file."""
--> 187         file, cached = self._acquire_with_cache_info(needs_lock)
    188         try:
    189             yield file

~\AppData\Local\Continuum\miniconda3\envs\dibecs_6.0.1\lib\site-packages\xarray\backends\file_manager.py in _acquire_with_cache_info(self, needs_lock)
    203                     kwargs = kwargs.copy()
    204                     kwargs["mode"] = self._mode
--> 205                 file = self._opener(*self._args, **kwargs)
    206                 if self._mode == "w":
    207                     # ensure file doesn't get overriden when opened again

src\netCDF4\_netCDF4.pyx in netCDF4._netCDF4.Dataset.__init__()

src\netCDF4\_netCDF4.pyx in netCDF4._netCDF4._get_grps()

src\netCDF4\_netCDF4.pyx in netCDF4._netCDF4.Group.__init__()

src\netCDF4\_netCDF4.pyx in netCDF4._netCDF4._get_vars()

src\netCDF4\_netCDF4.pyx in netCDF4._netCDF4._ensure_nc_success()

RuntimeError: NetCDF: HDF error
```

**Comment by OriolAbril** [comment] 2022-08-08 22:18
Is there something we can do to fix this?

**Comment by michaelosthege** [comment] 2022-08-08 23:57
While I never had this problem again, I do recall several instances where recent NetCDF4 and h5py versions caused incompatibilities.
Generally I would recommend to make more releases on smaller increments, because every time there's a new release the conda-gorge magic happens and could reveal/fix incompatibilities.

**Comment by tomicapretto** [comment] 2023-09-13 14:24
@OriolAbril should this still be open? Maybe we can close it and reopen if someone comes with a reproducible example?

**Comment by OriolAbril** [comment] 2023-09-13 14:37
we also depend on h5necdf instead of netcdf4 thanks to @varchasgopalaswamy great contribution on #2122 which seems to be more reliable. So I do think it is safe to close and will do it. To anyone reading this, please don't hesitate to comment here or open new issues if you face anything similar.

**Closed by OriolAbril** 2023-09-13 14:37 UTC
