### ISSUE TITLE
plot_density function doesn't work for predictive prior unless credible interval is specified as 1

### ISSUE THREAD

**Issue by parksj10** [arviz-devs/arviz#1145] opened 2020-04-10 19:45 UTC
**Describe the bug**
When attempt to plot prior predictive distributions using plot_density function, plots show nothin unless credible interval is defined as 1

**To Reproduce**
`az.plot_density(prior,credible_interval=1)`
![image](https://user-images.githubusercontent.com/28692761/79018495-ce673500-7b28-11ea-8976-d726bda23483.png)

`az.plot_density(prior)`
![image](https://user-images.githubusercontent.com/28692761/79018467-bc859200-7b28-11ea-874c-1e10be4183dd.png)

**Expected behavior**
Expected that the plot should only contain the 0.89 credible interval, instead of blank plots

**Additional context**
arviz                0.7.0
pymc3                3.8
matplotlib           3.2.1

also using
`%matplotlib inline`

**Comment by aloctavodia** [comment] 2020-04-13 12:55
Hi @parksj10 thanks for taking the time to report this issue. I an not able to reproduce the problem. Could you post a reproducible example? I think you are trying to reproduce some code from statistical rethinking, is that right? Notice that the default credible interval in ArviZ is 0.94

**Comment by parksj10** [comment] 2020-04-13 16:25
Hi @aloctavodia 

No problem, sorry for the incomplete report, I'm still getting the hang of this :), anyways here's an ipynb with the data that should be runnable, I've also included a pip freeze in case you're interested

[Archive 2.zip](https://github.com/arviz-devs/arviz/files/4470464/Archive.2.zip)

**Comment by aloctavodia** [comment] 2020-04-13 16:56
Thanks for the example. Now I can confirm the issue. I will work on this and keep you posted. In the meantime you can do this:

`data = az.from_pymc3(posterior_1, prior=prior, posterior_predictive=posterior_pred_1)`

data will be an [ArviZ's InferenceData](https://arviz-devs.github.io/arviz/notebooks/InferenceDataCookbook.html) object

you can then pass it to arviz functions, for example.

`az.summary(data)` 

or `az.plot_density(data.prior)` or equivalently `az.plot_density(data, group=prior)` the default group is `posterior` thus `az.plot_density(data)` will give you a plot of the posterior. 

One tip, you can globally set a few arviz parameters using `az.rcParams`, so for example you can add `az.rcParams["stats.credible_interval"] = 0.89` at the begging, and then all plots and summaries will use this value instead of the default one (0.94).

My guess about statistical rethinking is because the credible interval of .89 is used by the book even when the most common default value is 0.95. ArviZ and Statistical rethinking both uses non common values to remind user of the arbitrary nature of any default value.

Your report was very good. You clearly stated the problem and the excepted outcome. A reproducible (simple) example always helps.

**Comment by parksj10** [comment] 2020-04-13 17:23
Thanks for all the awesome help! Implementing all of that I perhaps see why you weren't reproducing the issue initially, will use the InferenceData object for now... :)

**Comment by aloctavodia** [comment] 2020-11-16 12:40
Closing as the recommended workflow is to generate the idata object.

**Closed by aloctavodia** 2020-11-16 12:40 UTC
