### ISSUE TITLE
plot_forest only plots first element

### ISSUE THREAD

**Issue by fonnesbeck** [arviz-devs/arviz#1023] opened 2020-01-23 17:47 UTC
I'm using ArviZ 0.6.1 on Debian Linux and Python 3.7, attempting to plot the trace of a vector of parameters derived from sampling a VI approximation. However, only the first element of the parameter vector is plotted:

![image](https://user-images.githubusercontent.com/81476/73009278-dd660300-3dd5-11ea-8d25-f69e296cbc90.png)

I can confirm that beta is indeed vector-valued:

![image](https://user-images.githubusercontent.com/81476/73009345-fa023b00-3dd5-11ea-8f10-d741b97bfd6b.png)

Oddly, I cannot replicate this behavior on other platforms (e.g. colab using 0.6.1).

**Comment by fonnesbeck** [comment] 2020-01-23 18:26
I can confirm that this also occurs on the current master.

**Comment by ahartikainen** [comment] 2020-01-23 18:42
How do you transform your samples to inferencedata? We usually assume `chain,draw,*shape` for the input (or 1D, which is then just `draw` (maybe))

**Comment by fonnesbeck** [comment] 2020-01-23 18:52
I'm just passing the result of `approx.sample()` to `plot_forest`, and that object is:

    <MultiTrace: 1 chains, 500 iterations, 8 variables>

**Comment by fonnesbeck** [comment] 2020-01-23 18:53
Doing an explicit cast via `az.from_pymc3(vi_trace)` does not fix the problem.

**Comment by aloctavodia** [comment] 2020-01-23 19:18
I can confirm this. It is also affecting other plots (but not summary). I can work on this, but not until tomorrow.

**Comment by fonnesbeck** [comment] 2020-01-23 19:34
OK, cool--no rush. Glad its not just me.

**Comment by OriolAbril** [comment] 2020-01-23 20:17
> Doing an explicit cast via `az.from_pymc3(vi_trace)` does not fix the problem.

Are all the variables in the `InferenceData`? What is the output of `az.from_pymc3(vi_trace).posterior`?

> It is also affecting other plots (but not summary). I can work on this, but not until tomorrow.

This seems to indicate the issue is in `plot_forest`, I just want to confirm `from_pymc3` is working fine.

**Comment by fonnesbeck** [comment] 2020-01-23 21:06
Passing the trace to summary generates a table of all values, so since `from_pymc3` is being called there as well, it shouldn't be an issue with that function.

**Comment by aloctavodia** [comment] 2020-01-29 15:29
Closing as fixed by #1027

**Closed by aloctavodia** 2020-01-29 15:29 UTC
