### ISSUE TITLE
Installing arviz breaks pymc3 installation

### ISSUE THREAD

**Issue by lwahedi** [arviz-devs/arviz#594] opened 2019-02-20 21:48 UTC
**Describe the bug**
Installing Arviz breaks a pymc3 installation, which is unfortunate because they're built to be compatible. After installation, importing pymc3 throws the following error. 

> WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.

The reason is because arviz installation requires numpy==1.15 rather than numpy>=1.15. If you have 1.16, it uninstalls it and re-installs 1.15. It's annoying to fix. I ended up having to scrap the whole virtual environment and start over.

**To Reproduce**
Install arviz if you have any version of numpy other than 1.15, then import pymc3. 

**Expected behavior**
Do not force downgrade of numpy.

**Comment by ColCarroll** [comment] 2019-02-20 22:10
Thanks for the report! I can confirm that in the pypi released version, the requirements are:

```
matplotlib>=3.0
numpy==1.15
scipy
pandas
xarray
netcdf4
```
(this fixed a bug that used to exist in numpy)

The best solution would be cutting a release with only that removed, but the easiest solution would be cutting a new release off master asap.

**Comment by lwahedi** [comment] 2019-02-21 00:11
So does this mean that arviz will not work with either older or newer versions of numpy? That's good to know, because my workaround was just to install it either first, or without dependencies and then install the rest of the dependencies individually. But it may mean that if you plan to use arviz you should fix your numpy back to 1.15 in your docker/virtualenv/etc/. 
Might at least be worth a note in the documentation section on using arviz with pymc3 traces.

**Comment by canyon289** [comment] 2019-02-21 00:19
@lwahedi Apologies on this issue. It's definitely annoying

To answer your question, It will work with newer versions of numpy, this was a short term fix that we applied due to a numpy bug a couple months ago that was not supposed to make it into production.

We're going to cut a pypi release on Saturday to unpin numpy version (and introduce more features!)

For now the best option would be to install from github master.

Sorry for all the trouble, and we really appreciate you creating this issue

**Comment by canyon289** [comment] 2019-02-23 21:44
@lwahedi We released version 0.3.3 of arviz. On my local machine the release fixed the numpy pinning issue. 

Would you want to verify that it works locally for you as well?

![image](https://user-images.githubusercontent.com/7213793/53292021-24d0b300-3771-11e9-8920-ee172ab6aa97.png)

**Comment by canyon289** [comment] 2019-02-28 19:12
I believe this issue is fixed. Closing for now

**Closed by canyon289** 2019-02-28 19:12 UTC

**Comment by lwahedi** [comment] 2019-03-07 16:04
Sorry for disappearing, was traveling. But yes, it all works now. Thanks!
